# Battle Game
# Final Python Project
import random
import time
import turtle


screen = turtle.Screen()
feet = turtle.Turtle()

feet.shape("arrow")
feet.color("#FF0000")
feet.width(7.5)

screen.bgcolor("black")
feet.speed(1000)

hands = turtle.Turtle()

hands.shape("arrow")
hands.color("#FFFFFF")
hands.speed(100)

head = turtle.Turtle()

head.shape("arrow")
head.color("#234F1E")
head.speed(100)
head.width(20)

arms = turtle.Turtle()

arms.shape("arrow")
arms.color("#63C5DA")
arms.speed(1000)
arms.width(7.5)

legs = turtle.Turtle()

legs.shape("arrow")
legs.color("#FFFFFF")
legs.speed(100)

knee = turtle.Turtle()

knee.shape("arrow")
knee.color("#FFFFFF")
knee.speed(100)

elbow = turtle.Turtle()

elbow.shape("arrow")
elbow.color("#610C04")
elbow.speed(100)
elbow.width(7.5)

print("To start the game, type 'battleDungeon()'")

def battleDungeon():
    userhp = 0
    userbal = 0
    userdmg = 0
    userdis = 0
    boss1 = random.randint(1, 6)
    bosshp = 0
    bossdmg = 0
    boss2 = random.randint(1, 6)
    boss2hp = 0
    boss2dmg = 0
    firespell = 0
    waterspell = 0
    rockspell = 0
    fs = 0
    ws1 = 0
    ws2 = 0
    rs = 0
    print("Welcome to your worst nightmare..")
    time.sleep(2)
    ready = input("Are you ready to face the fears of beating DEATH itself? ")
    if ready.lower() == "yes":
        print ("Good, well, good luck..")
    else:
        print("You are not ready, but it is too late now.....")
    time.sleep(3)
    while True:
        userstats = input("Which class would you like between Berserker, Archer, and Mage? ")
        if userstats.lower() in ["berserker", "archer", "mage"]:
            break
            return "Great pick! Your class is " + str(userstats) + "!"
        else:
            print ("That is not a class!")
    if userstats.lower() == "mage":
        userhp = 35
        userdmg = 75
        userbal = 0
        print("Analyzing mage data..")
    elif userstats.lower() == "berserker":
        userhp = 90
        userbal = 0
        userdmg = 30
        print("Analyzing berserker data..")
    elif userstats.lower() == "archer":
        userhp = 50
        userbal = 0
        userdmg = 50
        print("Analyzing archer data..")
    else:
        print("Something has went wrong..")
    time.sleep(2)
    print(" ")
    print("                         <!>       ")
    print(" ")
    print("Do not mispell things.. they could cost you the victory!")
    print(" ")
    print("                         <!>")
    print(" ")
    time.sleep(3.5)
    if boss1 == 1:
        bosshp = 100
        bossdmg = 20
    if boss1 == 2:
        bosshp = 75
        bossdmg = 30
    if boss1 == 3:
        bosshp = 90
        bossdmg = 25
    if boss1 == 4:
        bosshp = 50
        bossdmg = 50
    if boss1 == 5:
        bosshp = 120
        bossdmg = 10
    if boss1 == 6:
        bosshp = 60
        bossdmg = 40
    if boss2 == 1:
        boss2hp = 90
        boss2dmg = 65
    if boss2 == 2:
        boss2hp = 100
        boss2dmg = 60
    if boss2 == 3:
        boss2hp = 120
        boss2dmg = 45
    if boss2 == 4:
        boss2hp = 135
        boss2dmg = 40
    if boss2 == 5:
        boss2hp = 150
        boss2dmg = 25
    if boss2 == 6:
        boss2hp = 200
        boss2dmg = 15
    time.sleep(2)
    print("Welcome, fellow adventurer...")
    name = input("What is your name, warrior? ")
    time.sleep(1)
    print("-------------------------------------")
    time.sleep(1)
    print(name + ", I can see it in you.. you are ready to fight your way through the dungeon")
    time.sleep(2)
    print("The reaper has haunted all towns for generations..")
    time.sleep(2)
    print("Those towns are now ghost towns")
    time.sleep(2)
    print("He left a message for you...")
    time.sleep(5)
    print("'death'")
    time.sleep(3)
    print("Your enemy has " + str(bosshp) + " hitpoints")
    time.sleep(0.5)
    print("-------------------------------")
    time.sleep(0.5)
    print("You have " + str(userhp) + " hitpoints")
    hands.penup()
    hands.forward(450)
    hands.left(90)
    hands.forward(350)
    hands.pendown()
    hands.begin_fill()
    hands.left(90)
    hands.forward(400)
    hands.left(90)
    hands.forward(5)
    hands.left(90)
    hands.forward(400)
    hands.left(90)
    hands.forward(5)
    hands.end_fill()
    hands.penup()
    hands.home()
    knee.penup()
    knee.forward(450)
    knee.left(90)
    knee.forward(350)
    knee.left(90)
    knee.forward(400)
    knee.left(90)
    knee.forward(5)
    knee.left(90)
    knee.forward(400)
    knee.left(90)
    knee.forward(5)
    knee.left(90)
    knee.forward(900)
    knee.pendown()
    knee.begin_fill()
    knee.left(90)
    knee.forward(5)
    knee.left(90)
    knee.forward(400)
    knee.left(90)
    knee.forward(5)
    knee.left(90)
    knee.forward(400)
    knee.end_fill()
    knee.penup()
    knee.home()
    legs.penup()
    legs.forward(450)
    legs.left(90)
    legs.forward(350)
    legs.pendown()
    legs.left(90)
    legs.forward(400)
    legs.left(90)
    legs.forward(5)
    legs.left(90)
    legs.forward(400)
    legs.left(90)
    legs.forward(5)
    legs.penup()
    legs.left(90)
    legs.forward(900)
    legs.pendown()
    legs.left(90)
    legs.forward(5)
    legs.left(90)
    legs.forward(400)
    legs.left(90)
    legs.forward(5)
    legs.left(90)
    legs.forward(400)
    legs.penup()
    legs.home()
    head.penup()
    head.home()
    head.left(180)
    head.forward(500)
    head.left(90)
    head.forward(250)
    head.pendown()
    head.left(90)
    head.forward(1000)
    head.penup()
    head.home
    arms.penup()
    arms.back(300)
    arms.right(90)
    arms.forward(100)
    arms.pendown()
    feet.penup()
    feet.forward(300)
    feet.right(90)
    feet.forward(100)
    feet.pendown()
    amt = 45
    while amt > 0:
        arms.right(8)
        arms.forward(8)
        feet.right(8)
        feet.forward(8)
        amt = amt - 1
    arms.penup()
    arms.right(90)
    arms.forward(25)
    arms.pendown()
    arms.forward(1)
    arms.penup()
    arms.forward(48)
    arms.pendown()
    arms.forward(1)
    arms.penup()
    arms.home()
    feet.penup()
    feet.right(90)
    feet.forward(115)
    feet.back(25)
    feet.pendown()
    feet.back(1)
    feet.penup()
    feet.back(48)
    feet.pendown()
    feet.back(1)
    feet.penup()
    feet.home()
    hands.forward(1000)
    feet.forward(1000)
    arms.forward(1000)
    head.forward(1000)
    legs.forward(1000)
    knee.forward(1000)
    elbow.penup()
    elbow.home()
    elbow.forward(1000)
    defends = 3
    if userstats.lower() in ["mage", "archer"]:
        print("Since you are a " + userstats.lower() + ", you get to hit your enemy first!")
        while bosshp > 0 and userhp > 0:
            time.sleep(2)
            wish = input("Do you wish to attack or defend? ")
            if wish.lower() == "attack":
                print("You dealt " + str(userdmg) + " hitpoints to the boss!")
                time.sleep(2)
                bosshp = bosshp - userdmg
                print("The reaper now has " + str(bosshp) + " hit points left!")
                if bosshp <= 120 and bosshp > 90:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(300)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(300)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                if bosshp <= 90 and bosshp > 60:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(200)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(200)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                if bosshp <= 60 and bosshp > 30:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(100)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(100)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                if bosshp <= 30 and bosshp > 15:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(50)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(50)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                if bosshp <= 0:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(0.5)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(0.5)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                    print("The reaper's eyes close as he refuses to believe your victory!")
            if wish.lower() == "defend" and defends > 0:
                print("You feel the power!")
                time.sleep(2)
                userhp = userhp * 1.15
                print("You now have " + str(userhp) + " hitpoints!")
                defends = defends - 1
            if wish.lower() not in ["defend", "attack"]:
                print("You have either defended too many times, or the input is invalid. Now it's the bosses turn!")
            if bosshp > 0:
                time.sleep(2)
                print("The reaper is INFURIATED and STRIKES back!")
                time.sleep(2)
                print("He hits you for " + str(bossdmg) + " hitpoints")
                time.sleep(2)
                userhp = userhp - bossdmg
                print("You now have " + str(userhp) + " hitpoints")
                if userhp <= 90 and userhp > 72:
                    knee.clear()
                    knee.home()
                    knee.penup()
                    knee.forward(450)
                    knee.left(90)
                    knee.forward(350)
                    knee.left(90)
                    knee.forward(400)
                    knee.left(90)
                    knee.forward(5)
                    knee.left(90)
                    knee.forward(400)
                    knee.left(90)
                    knee.forward(5)
                    knee.left(90)
                    knee.forward(900)
                    knee.pendown()
                    knee.begin_fill()
                    knee.left(90)
                    knee.forward(5)
                    knee.left(90)
                    knee.forward(320)
                    knee.left(90)
                    knee.forward(5)
                    knee.left(90)
                    knee.forward(320)
                    knee.end_fill()
                    knee.penup()
                    knee.home()
                    knee.forward(1000)
                if userhp <= 72 and userhp > 54:
                    knee.clear()
                    knee.home()
                    knee.penup()
                    knee.forward(450)
                    knee.left(90)
                    knee.forward(350)
                    knee.left(90)
                    knee.forward(400)
                    knee.left(90)
                    knee.forward(5)
                    knee.left(90)
                    knee.forward(400)
                    knee.left(90)
                    knee.forward(5)
                    knee.left(90)
                    knee.forward(900)
                    knee.pendown()
                    knee.begin_fill()
                    knee.left(90)
                    knee.forward(5)
                    knee.left(90)
                    knee.forward(240)
                    knee.left(90)
                    knee.forward(5)
                    knee.left(90)
                    knee.forward(240)
                    knee.end_fill()
                    knee.penup()
                    knee.home()
                    knee.forward(1000)
                if userhp <= 54 and userhp > 36:
                    knee.clear()
                    knee.home()
                    knee.penup()
                    knee.forward(450)
                    knee.left(90)
                    knee.forward(350)
                    knee.left(90)
                    knee.forward(400)
                    knee.left(90)
                    knee.forward(5)
                    knee.left(90)
                    knee.forward(400)
                    knee.left(90)
                    knee.forward(5)
                    knee.left(90)
                    knee.forward(900)
                    knee.pendown()
                    knee.begin_fill()
                    knee.left(90)
                    knee.forward(5)
                    knee.left(90)
                    knee.forward(160)
                    knee.left(90)
                    knee.forward(5)
                    knee.left(90)
                    knee.forward(160)
                    knee.end_fill()
                    knee.penup()
                    knee.home()
                    knee.forward(1000)
                if userhp <= 36 and userhp > 18:
                    knee.clear()
                    knee.home()
                    knee.penup()
                    knee.forward(450)
                    knee.left(90)
                    knee.forward(350)
                    knee.left(90)
                    knee.forward(400)
                    knee.left(90)
                    knee.forward(5)
                    knee.left(90)
                    knee.forward(400)
                    knee.left(90)
                    knee.forward(5)
                    knee.left(90)
                    knee.forward(900)
                    knee.pendown()
                    knee.begin_fill()
                    knee.left(90)
                    knee.forward(5)
                    knee.left(90)
                    knee.forward(80)
                    knee.left(90)
                    knee.forward(5)
                    knee.left(90)
                    knee.forward(80)
                    knee.end_fill()
                    knee.penup()
                    knee.home()
                    knee.forward(1000)
                if userhp <= 0:
                    knee.clear()
                    knee.home()
                    knee.penup()
                    knee.forward(450)
                    knee.left(90)
                    knee.forward(350)
                    knee.left(90)
                    knee.forward(400)
                    knee.left(90)
                    knee.forward(5)
                    knee.left(90)
                    knee.forward(400)
                    knee.left(90)
                    knee.forward(5)
                    knee.left(90)
                    knee.forward(900)
                    knee.pendown()
                    knee.begin_fill()
                    knee.left(90)
                    knee.forward(5)
                    knee.left(90)
                    knee.forward(0.5)
                    knee.left(90)
                    knee.forward(5)
                    knee.left(90)
                    knee.forward(0.5)
                    knee.end_fill()
                    knee.penup()
                    knee.home()
                    knee.forward(1000)
                    print ("You shout on the ground as you bleed to death")
                    time.sleep(3)
                    print ("'His scythe was too powerful' You say as your final words..")
    defendsb = 3      
    if userstats.lower() == "berserker":
        print("Because you are a " + userstats.lower() + ", the boss strikes first!")
        while bosshp > 0 and userhp > 0:
            time.sleep(2)
            print("The reaper rages towards you..")
            time.sleep(2)
            print("He hits you for " + str(bossdmg) + " hitpoints")
            userhp = userhp - bossdmg
            print("You now have " + str(userhp) + " hitpoints")
            if userhp <= 90 and userhp > 72:
                knee.clear()
                knee.home()
                knee.penup()
                knee.forward(450)
                knee.left(90)
                knee.forward(350)
                knee.left(90)
                knee.forward(400)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(400)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(900)
                knee.pendown()
                knee.begin_fill()
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(320)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(320)
                knee.end_fill()
                knee.penup()
                knee.home()
                knee.forward(1000)
            if userhp <= 72 and userhp > 54:
                knee.clear()
                knee.home()
                knee.penup()
                knee.forward(450)
                knee.left(90)
                knee.forward(350)
                knee.left(90)
                knee.forward(400)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(400)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(900)
                knee.pendown()
                knee.begin_fill()
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(240)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(240)
                knee.end_fill()
                knee.penup()
                knee.home()
                knee.forward(1000)
            if userhp <= 54 and userhp > 36:
                knee.clear()
                knee.home()
                knee.penup()
                knee.forward(450)
                knee.left(90)
                knee.forward(350)
                knee.left(90)
                knee.forward(400)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(400)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(900)
                knee.pendown()
                knee.begin_fill()
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(160)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(160)
                knee.end_fill()
                knee.penup()
                knee.home()
                knee.forward(1000)
            if userhp <= 36 and userhp > 18:
                knee.clear()
                knee.home()
                knee.penup()
                knee.forward(450)
                knee.left(90)
                knee.forward(350)
                knee.left(90)
                knee.forward(400)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(400)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(900)
                knee.pendown()
                knee.begin_fill()
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(80)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(80)
                knee.end_fill()
                knee.penup()
                knee.home()
                knee.forward(1000)
            if userhp <= 0:
                knee.clear()
                knee.home()
                knee.penup()
                knee.forward(450)
                knee.left(90)
                knee.forward(350)
                knee.left(90)
                knee.forward(400)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(400)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(900)
                knee.pendown()
                knee.begin_fill()
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(0.5)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(0.5)
                knee.end_fill()
                knee.penup()
                knee.home()
                knee.forward(1000)
                print("You start to wobble as you fall to the ground..")
                time.sleep(3)
                print("You fall to the ground and die..")
            time.sleep(2)
            if userhp > 0:
                wish2 = input("Do you wish to attack or defend? ")
                if wish2.lower() == "attack":
                    print("You thrust forward and rush to hit your enemy!")
                    time.sleep(2)
                    print("You dealt " + str(userdmg) + " hitpoints to the reaper!")
                    bosshp = bosshp - userdmg
                    print("The boss now has " + str(bosshp) + " hitpoints")
                    if bosshp <= 120 and bosshp > 90:
                        hands.clear()
                        hands.home()
                        hands.penup()
                        hands.forward(450)
                        hands.left(90)
                        hands.forward(350)
                        hands.pendown()
                        hands.begin_fill()
                        hands.left(90)
                        hands.forward(300)
                        hands.left(90)
                        hands.forward(5)
                        hands.left(90)
                        hands.forward(300)
                        hands.left(90)
                        hands.forward(5)
                        hands.end_fill()
                        hands.penup()
                        hands.home()
                        hands.forward(1000)
                    if bosshp <= 90 and bosshp > 60:
                        hands.clear()
                        hands.home()
                        hands.penup()
                        hands.forward(450)
                        hands.left(90)
                        hands.forward(350)
                        hands.pendown()
                        hands.begin_fill()
                        hands.left(90)
                        hands.forward(200)
                        hands.left(90)
                        hands.forward(5)
                        hands.left(90)
                        hands.forward(200)
                        hands.left(90)
                        hands.forward(5)
                        hands.end_fill()
                        hands.penup()
                        hands.home()
                        hands.forward(1000)
                    if bosshp <= 60 and bosshp > 30:
                        hands.clear()
                        hands.home()
                        hands.penup()
                        hands.forward(450)
                        hands.left(90)
                        hands.forward(350)
                        hands.pendown()
                        hands.begin_fill()
                        hands.left(90)
                        hands.forward(100)
                        hands.left(90)
                        hands.forward(5)
                        hands.left(90)
                        hands.forward(100)
                        hands.left(90)
                        hands.forward(5)
                        hands.end_fill()
                        hands.penup()
                        hands.home()
                        hands.forward(1000)
                    if bosshp <= 30 and bosshp > 15:
                        hands.clear()
                        hands.home()
                        hands.penup()
                        hands.forward(450)
                        hands.left(90)
                        hands.forward(350)
                        hands.pendown()
                        hands.begin_fill()
                        hands.left(90)
                        hands.forward(50)
                        hands.left(90)
                        hands.forward(5)
                        hands.left(90)
                        hands.forward(50)
                        hands.left(90)
                        hands.forward(5)
                        hands.end_fill()
                        hands.penup()
                        hands.home()
                        hands.forward(1000)
                    if bosshp <= 0:
                        hands.clear()
                        hands.home()
                        hands.penup()
                        hands.forward(450)
                        hands.left(90)
                        hands.forward(350)
                        hands.pendown()
                        hands.begin_fill()
                        hands.left(90)
                        hands.forward(0.5)
                        hands.left(90)
                        hands.forward(5)
                        hands.left(90)
                        hands.forward(0.5)
                        hands.left(90)
                        hands.forward(5)
                        hands.end_fill()
                        hands.penup()
                        hands.home()
                        hands.forward(1000)
                        print("The reaper starts to hyperventilate as he falls to the ground..")
                        time.sleep(3)
                        print("Good job..")
                elif wish2.lower() == "defend" and defendsb > 0:
                    print("You feel the power!")
                    time.sleep(2)
                    userhp = userhp * 1.5
                    print("You now have " + str(userhp) + " hitpoints!")
                    defendsb = defendsb - 1
                else:
                    print("You have either defended too many times, or the input is invalid. Now the boss will go!")
    if userhp > 0 and bosshp <= 0:
        userhp = userhp * 2.5
        userbal = userbal + 100
        print("Since you surived the first round, you got healed by an angel and now have " + str(userhp) + " hitpoints!")
    while True and userhp > 0 and bosshp <= 0:
        buy = input("Do you wish to buy new items to increase your damage and hitpoints? ")
        if  buy.lower() == "yes" and userstats.lower() == "berserker":
            print("Because you chose beserker, the available items in the shop are a Machette, Body armor, and daggers")
            time.sleep(1)
            print("You have " + str(userbal) + " coins!")
            time.sleep(2)
            print("Machette increases your damage by 15 and costs 50 coins")
            print("Body armor increases your hitpoints by 30 and costs 75 coins")
            print("Daggers increase your damage by 25, but decrease your hitpoints by 10 and costs 50 coins")
            time.sleep(3)
            bought = input("Which item would you like to buy? ")
            if bought.lower() == "machette" and userbal > 50:
                userbal = userbal - 50
                userdmg = userdmg + 15
                print("You feel stronger as you wield your machette!")
                break
            if bought.lower() == "body armor" and userbal > 75:
                userbal = userbal - 75
                userhp = userhp + 30
                print("The body armor motivates you, you are now stronger!")
                break
            if bought.lower() == "daggers" and userbal > 50 and userhp > 10:
                userbal = userbal - 50
                userhp = userhp - 10
                userdmg = userdmg + 25
                print("You feel sudden pain as you lose 10 hitpoints, be regain the strength with your daggers!")
                break
            else:
                print("You are either too poor, don't have the hitpoints to buy that, or mistyped something..")
                break
        if buy.lower() == "yes" and userstats.lower() == "archer":
            print("Because you chose archer, the available items in the shop are a strong bow, archer's helmet, and speedy boots")
            time.sleep(1)
            print("You have " + str(userbal) + " coins!")
            time.sleep(3)
            print("The strong bow increases your damage by 15 and costs 50 coins!")
            print("The archer's helmet increaases your hitpoints by 10 and costs 30 coins!")
            print("Speedy boots increase you hitpoints by 25, but decrease your damage by 10 and cost 60 coins!")
            time.sleep(3)
            boughta = input("Which item would you like to buy? ")
            if boughta.lower() == "strong bow" and userbal > 50:
                userdmg = userdmg + 15
                userbal = userbal - 50
                print("You feel strong with your new bow and have " + str(userbal) + " coins left!")
                break
            if boughta.lower() in ["archer's helmet", "archers helmet"]:
                userhp = userhp + 10
                userbal = userbal - 30
                print("You feel stronger with your new helmet and have " + str(userbal) + " coins left!")
                break
            if boughta.lower() == "speedy boots":
                userhp = userhp + 25
                userdmg = userdmg - 10
                userbal = userbal -60
                print("You stand strong with your new boots and prepare for battle..")
                time.sleep(2)
                print("You now have " + str(userbal) + " coins left!")
                break
            else:
                print("You are either too poor, don't have the hitpoints to buy that, or mistyped something..")
                break
        if buy.lower() == "yes" and userstats.lower() == "mage":
            print("Because you chose mage, the available abilities in the shop are firespell, waterspell, and rockspell")
            time.sleep(2)
            print("You have " + str(userbal) + " coins!")
            time.sleep(3)
            print("The firespell is an ability that does 90 damage to your opponent and costs 90 coins!")
            print("The waterspell heals you for 10 hitpoints and does 55 damage to your oppenent. It costs 90 coins!")
            print("The rockspell heals you for 20 hitpoints and costs 75 coins!")
            time.sleep(4)
            boughtm = input("Which ability would you like to buy? ")
            if boughtm.lower() == "firespell":
                firespell = 1
                fs = 90
                userbal = userbal - 90
                print("You feel stronger with your new firespell!")
                break
            if boughtm.lower() == "waterspell":
                waterspell = 1
                userbal = userbal - 90
                ws1 = 10
                ws2 = 55
                print("You feel stronger with your new waterspell!")
                break
            if boughtm.lower() == "rockspell":
                rockspell = 1
                userbal = userbal - 75
                rs = 20
                print("You feel stronger with your new rockspell!")
                break
            else:
                print("You are either too poor, don't have the hitpoints to buy that, or mistyped something..")
                break
    if userhp > 0 and bosshp <= 0:
        time.sleep(2)
        print("You shall now face the fates of FLOOR 2 of the dungeon. ")
        feet.clear()
        feet.home()
        feet.penup()
        feet.forward(1000)
        elbow.home()
        elbow.penup()
        elbow.forward(300)
        elbow.right(90)
        elbow.forward(100)
        elbow.pendown()
        amt3 = 45
        while amt3 > 0:
            elbow.pendown()
            elbow.right(8)
            elbow.forward(8)
            amt3 = amt3 - 1
        elbow.penup()
        elbow.right(90)
        elbow.forward(115)
        elbow.back(25)
        elbow.pendown()
        elbow.back(1)
        elbow.penup()
        elbow.back(48)
        elbow.pendown()
        elbow.back(1)
        elbow.penup()
        elbow.home()
        elbow.forward(1000)
        time.sleep(2)
        print("Hellfire isn't happy that the reaper died and wishes to avenge him")
        time.sleep(3)
        print("He only comes with two words...")
        time.sleep(4)
        print("____    |---|  |---|  |---x")
        print("|       |   |  |   |  |   |")
        print("|   _   |   |  |   |  |   |")
        print("|   |   |   |  |   |  |   |")
        print("|----   |___|  |___|  |___/")
        time.sleep(4)
        print("--------------------------------")
        print("|      |   |  |---  |   /")
        print("|      |   |  |     |  /")
        print("|      |   |  |     |-")
        print("|      |   |  |     | x")
        print("|____  |___|  |___  |  xx")
        time.sleep(2)
        print("I hope you're ready...")
        print("Hellfire has " + str(boss2hp) + " hitpoints!")
    while boss2hp > 0 and userhp > 0:
        if firespell == 1 and userstats.lower() == "mage":
            wishattackm = input("Which move would you like to use between defend and firespell? ")
            if wishattackm.lower() == "firespell":
                print("You lunge foward at Hellfire and hit him")
                time.sleep(2)
                boss2hp = boss2hp - fs
                print("Hellfire only has " + str(boss2hp) + " hitpoints left!")
                if boss2hp <= 200 and boss2hp > 150:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(300)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(300)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                if boss2hp <= 150 and boss2hp > 100:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(200)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(200)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                if boss2hp <= 100 and boss2hp > 50:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(100)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(100)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                if boss2hp <= 50 and boss2hp > 25:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(50)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(50)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                if boss2hp <= 0:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(0.5)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(0.5)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                    print("Hellfire falls to the ground as he closes his eyes in disbelief")
            if wishattackm.lower() == "defend":
                print("You feel growth as you become stronger!")
                userhp = userhp * 1.25
                print("You now have " + str(userhp) + " hitpoints!")
        if waterspell == 1 and userstats.lower() == "mage":
            wishattackm2 = input("Which move would you like to use between attack, defend, and waterspell ")
            if wishattackm2.lower() == "attack":
                boss2hp = boss2hp - userdmg
                print("Hellfire takes the attack and is now at " + str(boss2hp) + " hitpoints left!")
                time.sleep(2)
                if boss2hp <= 200 and boss2hp > 150:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(300)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(300)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                if boss2hp <= 150 and boss2hp > 100:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(200)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(200)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                if boss2hp <= 100 and boss2hp > 50:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(100)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(100)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                if boss2hp <= 50 and boss2hp > 25:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(50)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(50)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                if boss2hp <= 0:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(0.5)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(0.5)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                    print("Hellfire falls to the ground as he closes his eyes in disbelief")
            if wishattackm2.lower() == "defend":
                userhp = userhp * 1.25
                print("You feel power and you now have " + str(userhp) + " hitpoints!")
                time.sleep(2)
            if wishattackm2.lower() == "waterspell":
                userhp = userhp + ws1
                boss2hp = boss2hp - ws2
                print("You feel stronger as you now have " + str(userhp) + " hitpoints!")
                time.sleep(2)
                print("Hellfire takes a hit and is now at " + str(boss2hp) + " hitpoints!")
                if boss2hp <= 200 and boss2hp > 150:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(300)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(300)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                if boss2hp <= 150 and boss2hp > 100:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(200)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(200)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                if boss2hp <= 100 and boss2hp > 50:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(100)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(100)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                if boss2hp <= 50 and boss2hp > 25:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(50)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(50)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                if boss2hp <= 0:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(0.5)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(0.5)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                    print("hellfire falls to the ground as he closes his eyes in disbelief")
        if rockspell == 1 and userstats.lower() == "mage":
            wishattackm3 = input("Which move would you like to use between attack, defend, and rockspell ")
            if wishattackm3 == "attack":
                boss2hp = boss2hp - userdmg
                print("Hellfire takes the attack and is now at " + str(boss2hp) + " hitpoints!")
                time.sleep(2)
                if boss2hp <= 200 and boss2hp > 150:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(300)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(300)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                if boss2hp <= 150 and boss2hp > 100:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(200)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(200)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                if boss2hp <= 100 and boss2hp > 50:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(100)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(100)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                if boss2hp <= 50 and boss2hp > 25:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(50)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(50)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                if boss2hp <= 0:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(0.5)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(0.5)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                    print("Hellfire falls to the ground as he closes his eyes in disbelief")
            if wishattackm3 == "defend":
                userhp = userhp * 1.25
                print("You grow stronger and now you have " + str(userhp) + " hitpoints!")
                time.sleep(2)
            if wishattackm3 == "rockspell":
                userhp = userhp + rs
                print("You get empowered with your new spell and are at " + str(userhp) + " hitpoints!")
                time.sleep(2)
        if userstats.lower() == "berserker":
            wishattackb = input("Which move would you like to use between attack and defend ")
            if wishattackb.lower() == "attack":
                boss2hp = boss2hp - userdmg
                print("Hellfire takes the hit and is now at " + str(boss2hp) + " hitpoints!")
                time.sleep(2)
                if boss2hp <= 200 and boss2hp > 150:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(300)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(300)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                if boss2hp <= 150 and boss2hp > 100:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(200)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(200)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                if boss2hp <= 100 and boss2hp > 50:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(100)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(100)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                if boss2hp <= 50 and boss2hp > 25:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(50)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(50)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                if boss2hp <= 0:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(0.5)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(0.5)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                    print("Hellfire falls to the ground in disbelief as he closes his eyes.")
            if wishattackb.lower() == "defend":
                userhp = userhp * 1.6
                print("You feel stronger and now have " + str(userhp) + " hitpoints!")
                time.sleep(2)
        if userstats.lower() == "archer":
            wishattacka = input("Which move would you like to use between attack and defend ")
            if wishattacka == "attack":
                boss2hp = boss2hp - userdmg
                print("Hellfire takes the hit and is now at " + str(boss2hp) + " hitpoints!")
                time.sleep(2)
                if boss2hp <= 200 and boss2hp > 150:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(300)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(300)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                if boss2hp <= 150 and boss2hp > 100:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(200)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(200)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                if boss2hp <= 100 and boss2hp > 50:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(100)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(100)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                if boss2hp <= 50 and boss2hp > 25:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(50)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(50)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                if boss2hp <= 0:
                    hands.clear()
                    hands.home()
                    hands.penup()
                    hands.forward(450)
                    hands.left(90)
                    hands.forward(350)
                    hands.pendown()
                    hands.begin_fill()
                    hands.left(90)
                    hands.forward(0.5)
                    hands.left(90)
                    hands.forward(5)
                    hands.left(90)
                    hands.forward(0.5)
                    hands.left(90)
                    hands.forward(5)
                    hands.end_fill()
                    hands.penup()
                    hands.home()
                    hands.forward(1000)
                    print("Hellfire falls to the ground as he closes his eyes in debelief")
            if wishattacka == "defend":
                userhp = userhp * 1.25
                print("You grow stronger as you now have " + str(userhp) + " hitpoints!")
                time.sleep(2)
        if boss2hp > 0 and userhp > 0:
            print("Hellfire feels enraged as he lunges towards you..")
            time.sleep(2)
            userhp = userhp - boss2dmg
            print("You feel pain as you are now at " + str(userhp) + " hitpoints.")
            if userhp <= 90 and userhp > 72:
                knee.clear()
                knee.home()
                knee.penup()
                knee.forward(450)
                knee.left(90)
                knee.forward(350)
                knee.left(90)
                knee.forward(400)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(400)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(900)
                knee.pendown()
                knee.begin_fill()
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(320)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(320)
                knee.end_fill()
                knee.penup()
                knee.home()
                knee.forward(1000)
            if userhp <= 72 and userhp > 54:
                knee.clear()
                knee.home()
                knee.penup()
                knee.forward(450)
                knee.left(90)
                knee.forward(350)
                knee.left(90)
                knee.forward(400)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(400)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(900)
                knee.pendown()
                knee.begin_fill()
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(240)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(240)
                knee.end_fill()
                knee.penup()
                knee.home()
                knee.forward(1000)
            if userhp <= 54 and userhp > 36:
                knee.clear()
                knee.home()
                knee.penup()
                knee.forward(450)
                knee.left(90)
                knee.forward(350)
                knee.left(90)
                knee.forward(400)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(400)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(900)
                knee.pendown()
                knee.begin_fill()
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(160)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(160)
                knee.end_fill()
                knee.penup()
                knee.home()
                knee.forward(1000)
            if userhp <= 36 and userhp > 18:
                knee.clear()
                knee.home()
                knee.penup()
                knee.forward(450)
                knee.left(90)
                knee.forward(350)
                knee.left(90)
                knee.forward(400)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(400)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(900)
                knee.pendown()
                knee.begin_fill()
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(80)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(80)
                knee.end_fill()
                knee.penup()
                knee.home()
                knee.forward(1000)
            if userhp <= 0:
                knee.clear()
                knee.home()
                knee.penup()
                knee.forward(450)
                knee.left(90)
                knee.forward(350)
                knee.left(90)
                knee.forward(400)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(400)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(900)
                knee.pendown()
                knee.begin_fill()
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(0.5)
                knee.left(90)
                knee.forward(5)
                knee.left(90)
                knee.forward(0.5)
                knee.end_fill()
                knee.penup()
                knee.home()
                knee.forward(1000)
                time.sleep(2)
                print("You fall to the ground as hellfire stares you down..")
                time.sleep(3)
                print("'You Lose.' he says with pride")



                
